name: Hoaxify Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: './react/package-lock.json'
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.4
      with:
        # The Java version to make available on the path. Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x). Early access versions can be specified in the form of e.g. 14-ea, 14.0.0-ea, or 14.0.0-ea.28
        java-version: 1.8
        
    - run: npm ci 
      working-directory: ./react
    - run: npm run build --if-present
      working-directory: ./react
    
    - name: copy react to spring static resources
      run: |
        mkdir -p ws/src/main/resources/static
        cp -a react/build/. ws/src/main/resources/static/
        
        
    - name: Build spring
      run: mvn -B package --file pom.xml
      working-directory: ./ws
      
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{secrets.USERNAME}}
        server: ${{secrets.IP}}
        ssh_private_key: ${{secrets.SSH}}
        local_path: ws/target/ws-0.0.1-SNAPSHOT.jar
        remote_path: /home/serhatbalki97
